### ISSUE TITLE
Final CSP Project Plan

### ISSUE THREAD

**Issue by Akhil353** [Akhil353/student#10]
Messaging Platform added feature: _**Sort messages based on certain features**_
---
Akhil:
- [x] Decide what are the most important features that differentiates messages (Finish by 5/19)
- [x] Add the sorting feature on backend (Finish by 5/22)
    - Add a separate function for each sorting type
- [x] Reduce time complexity of sorting program (Finish by 5/24)

Arnav: 
- [x]  Figure out the best way to sort messages(Finish by 5/18)
   - Sort by date, Sort by likes, etc.
- [x] Implement the parsing algorithm for the messages (Finish by 5/21)
   - Iterate through the 2D array to allow for sorting based on features
   - ![image_720](https://github.com/Akhil353/student/assets/106125268/b44c7d9c-7134-4dd0-95d2-3c699b18b106)

- [ ] Deployment of backend (Finish by 5/25)

What the program gains from deployment:
 - Multiple people can message in real-time
 - Users can see each other's messages

Requirements that are fulfilled:
 - Loops: Array is built using fetch POST function
 - Sorting/Searching: Messages will be sorted based on the selected feature
 - Big O optimization: The best sorting algorithm will likely take O(nlogn) time as this is the time complexity needed for sorting based on a feature (Sort by likes).
 - 2D Iteration: Since the sorting algorithm will go through a big array with multiple smaller dictionaries inside (messages), the program will have to iterate through each feature of each message to sort based on a certain feature.
 - Deployment: By deploying the project, the messaging platform can have actual functionality, as people can see new messages from others in real time.
